apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
stringData:
#hardcode your passwrod here, this is not a good practice, you should use a secret manager to manage your secrets
  password: skavi-eks-testing-password!